export const metadata = {
  title: "blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div>this is all blogs layout may be side bar</div>
      <section>{children}</section>;
    </>
  );
}
